const ACTION_TYPES = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_USER_NAME:"GET_USER_NAME",
  CREATE_USER:"CREATE_USER",
  GET_ALL_VEHICULES: "GET_ALL_VEHICULES",
  CREATE_VEHICULE:"CREATE_VEHICULE",
}
    
export default ACTION_TYPES;