const ACTION_TYPES = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_USER_NAME:"GET_USER_NAME",
  CREATE_USER: "CREATE_USER",
  MODIFY_USER_SUCCESS: "MODIFY_USER_SUCCESS",
  MODIFY_USER_FAILURE: "MODIFY_USER_FAILURE",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE:"DELETE_USER_FAILURE",
  GET_ALL_VEHICULES: "GET_ALL_VEHICULES",
  GET_TYPE_VEHICULES: "GET_TYPE_VEHICULES",
  GET_NAME_VEHICULES: "GET_NAME_VEHICULES",
  GET_USER_VEHICULES:"GET_USER_VEHICULES",
  CREATE_VEHICULE: "CREATE_VEHICULE",
  MODIFY_VEHICULE_SUCCESS: "MODIFY_VEHICULE_SUCCESS",
  MODIFY_VEHICULE_FAILURE:"MODIFY_VEHICULE_FAILURE",
  DELETE_VEHICULE_SUCCESS: "DELETE_VEHICULE_SUCCESS",
  DELETE_VEHICULE_FAILURE:"DELETE_VEHICULE_FAILURE"
}
    
export default ACTION_TYPES;