const ACTION_TYPES = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_USER_NAME:"GET_USER_NAME",
  CREATE_USER: "CREATE_USER",
  MODIFY_USER_SUCCESS: "MODIFY_USER_SUCCESS",
  MODIFY_USER_FAILURE: "MODIFY_USER_FAILURE",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE:"DELETE_USER_FAILURE",
  GET_ALL_VEHICULES: "GET_ALL_VEHICULES",
  CREATE_VEHICULE:"CREATE_VEHICULE",
}
    
export default ACTION_TYPES;